version: "3.6"

networks:
  discordbot-net:
    driver: bridge

services:
  bot:
    container_name: bot
    build:
      dockerfile: Dockerfile
    environment:
      TOKEN: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX